services:
- redis-server
language:
- python
python:
- '3.6'
install:
- pip install pipenv
- pipenv install --dev
script:
- pipenv run pytest
deploy:
  provider: heroku
  api_key:
    secure: DKOZJ7kNC6eS2jHzEJoaEfvIsO+pQSL42RCqTwUECkXy44B7tdgkE6Tu7awtX5k+4ediEe/AYdkkHiZquFw1jt+galZSmN7LpEGySNsW0ec6b7tHwfvJEW+zV1b2/RDw1jD/yvBeF9Gc9bpDdY1TjJD4Gt1VDkax3iRmiPJ8WMNo+J27ECY6Brk341JsqBtERZyfI0nn59QpMT81tx3kHPGYtPDtkRW9ltuU5K6TahyszWlRWXjXCb7AWOwPxJBIL95ZXCJnfir8u/XvLnUb2G8j8is96sUAmmKNJNkI2kX2bt32ujqfCYgLM35y1G04ABMGKPTr96JJcJcyzSeZabBrOf95Srdi3GgmBFM0jlEJF/83R6U0yQzea6XfvqTuBwVbn3x/ludt3OFbqmwlo9dwFOLh+zR2Tj2Ixu1zs7jH80YsnApzC+BJRBd/bG9cVaXyGL80U8RG3dnzNItLlEbQpiYcDl6it0+ljg2JGWWzkvSg903vAPvsYhliVy7K7/Ox7Bz19HYckMo35P9N7hB/TpT+mzPUgixd9Y5P0hFmx+yQdbpAorW4WTL9ZQJuhQ88g/kfqcexxJJ4aGnBqM8nonsONWZrE7MnfidasyjdXyDvC4z17hDFgdC46NujQ6MGaTF6qs1ZHmthAXyRSQywJP8Dh4NvBHP1en1Qc48=
  app:
    master: comp307p1-staging
