matrix:
  include:
  - language: python
    python:
    - '3.6'
    install:
    - pip install pipenv
    - pipenv install
    script:
    - pytest
deploy:
  provider: heroku
  api_key:
    secure: SkXblYzmeyGz+4+ePvGmWehKBTXkd1ntkD0/RTpimWTaokiI4xbuCEgNw5RDTBjAoHJc5Qj9mBtk8OwTf0gIa3BB5rNyf6QS0xDdIMoGHB1QMXA00DXpTYUj4X/9N/nIsE5OPJUGOh6Y0vJY/rhbrmG/iPXQJch/pbSJFQYhwUm16A/yJToC+YMk6tGVpZsMeyN/zZcyFcWiZlTJi/rjnenCPtZ1aPVmBq1k9VkGDphAoaBcCLVG9DOWeN3yFEy7J77mDyazEz7c2yAwSDyHA9obuaPCwn2iN4YOHQoiKuO33hX9FVN6NaIIEV/9Ii0pwJjvqz/kjWqiNQm4YJq89uoGEKFVazVlnXqX/6tLZT5ul08xu5U9Xvu9GDwAtHotDY+AKLQP3dUImgXsDYFfVPskzL1e5yaVRqnJNH+6WPcSS35g7+014cTq7c2ovKrH5UdQPrLiugU9DoTSkYKB21l39F/u3v0f8OhCRxOx0bFAaobohZpki0k56GOFsJiI3F0CsqN1udrpqXCGF6ocLSGwTVcNv9/1Q3F/Ytf9dMZU9HZapg2/dsHGy9WgqVZ6CezCznBlQGoWMgk0xR1ug+pUrZsC9YDokrT/We3w4+L9KhiBnqmRlOoVJDF3yH9LY5ZfEnw9Qpcyi+zGaHWUfJt46G/8U4OtWNtqTTZuYLI=
  app:
    master: copm307p1-staging
