matrix:
  include:
  - language: python
    python:
    - '3.6'
    install:
    - pip install pipenv
    - pipenv install
    script:
    - pytest
deploy:
  provider: heroku
  api_key:
    secure: jn0dw+RcbebQuZc5Le2vQvCKk8uDcvIAbWGp5e/M/XxLz6Bo5/sb2bC1V0bVIPCMqh0S0eEVqN4y9F8dhdOYzeRnm2ebBt1Qmdpz4sZiZRua1HNB9EsiGS1H1c9TNnBjJhIvqzcYhnA207bwzTP67gdNywKarYotzTt1/CbwapRZyhbRzOt9exG4dfOu2JzUHYt/QAwe0+VF2sGRfI94Sx//3kNTWaC4X4kNvNpd9UCXkKtM8CNOPh7hts6VO/QaOiQnVC5pRxIMMuH+RJD+hVAPFDJnKATCpe7GVN2QzuON7wrqQkBIoZ1PFxJJz8cwOdCCjhDhnobFTxZ742s6DrQbyj2XAsc4pxT/A+seUAxgNWFt1+JNXozbnjg7e02aNByT5nLc6tRzCOa1ajTOWwqzr3zH22pdtI3FFJAp9JNlO9coYZoKQwX62gOQgDPKRa50XoAKSzeQhwRbtmLvs029aTUCfS1JL8D1sNmQhbgtY7Smg3hVlvmrGYpmDPKudAgd6HiF8Y+J+aqv4E5k0p7RnLYDZMAtm74EbAP4qIkBSOWT3rtPcVk7bKso6h81RbAu5TZNuhl8SjT+/DC0Wt4nxo1bZnfFfD1jSJNb61aicJzyVv7nJqkQus/g48IvjbeGBxDODuBrMKGdKBcLL+U71qH61WnKh6N11jsmvvo=
  app:
    master: comp307p1-staging
