matrix:
  include:
  - language: python
    python:
    - '3.6'
    install:
    - pip install pipenv
    - pipenv install
    script:
    - pytest
deploy:
  provider: heroku
  api_key:
    secure: q8r0l8rRLHBniHmedonKGNnjiJ2lQ3mxU3Poqjp6xa0o3IdfQGkARHA+YnwyobyXUStlWknrqAxeCNM/8UJUkMnBAJXpVe5LuV5/oYjjAdlpw0TRjtUi/X/E70B99kCI0OcMTLnEyQJCu28PlBx87su6l6aJbfCBff97qMUiC5mgLOiDvzQOur6BPdkBu+deOZbmFSlrlqEr4IWPkgTTm12ll1qMzpeKcsmlfssIKYlLJZRurtXAlnsokBjv9+lDZ/u/X39WwNfz+dt4OC5OCuF2Qni5+gE89CldlYdmNCXb6ozUcax+29NbHzSPsWjtWibroTmsp7xKHXSR+7RyA5w8N4tJQkqwAj/51DLjIbas+Bj2Mx5QN/Um2DsoPaGDW6ycLVczoDag74fwZ6KpzAfU/arRF3FbXPHFtlzYm/bbMWp5ZcgkPAhUDaFlSeuOoxMomdGm2A+rIPVNt8yMXsn5kmg1dSJF5NBKh6Wwzyz3Fyq1zCKMhdgxkpgSpgwJW7kRHtInZem0Bg1Yc+Razwpuv0uiqLQXpUGwm6S9VoIBcM+2lqb64lmn2DFj/mSXLjDJnSZ075Tmea7AfFkB07O6ilXEWW2nnSshRlGo0YzPHO3zetZKHriZ9qMDJr8o1+GGMnzUKCUkRBl69sQrhsV/QqObv7Jms7Svh0svJUU=
  app:
    master: copm307p1-staging
